global:
    scrape_interval: 1m
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
    - job_name: 'dht22'
      # the dht22 can be really slow
      scrape_timeout: 30s
      static_configs:
        - targets: [temperature:5000]

